language: c
script:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ocaml42+opam12
  - sudo apt-get update -qq
  - sudo apt-get install -qq opam ocaml-native-compilers camlp4-extra
  - export OPAMYES=1
  - opam init
  - eval `opam config env`
  - opam pin add -n -k path opam-query .
  - opam install --deps-only -d -t opam-query
  - opam install -d -t -v opam-query
